### ISSUE TITLE
Payment validation call accept.php controller without any check with the payment process steps?

### ISSUE THREAD

**Issue by IrvinT** [hipay/hipay-fullservice-sdk-prestashop#13]
Hi,

I have a problem with this module, can you tell me why there is no checks with the payment process steps? 

An order can be easily created by calling this controller, why the callback is not the validation controller?
How can i solve it?

Thanks a lot

**Comment by legithubdeaymeric** [comment]
Hello,

We take note of your message.
Thank you for your feedback.

Can we continue the conversation by email: aberthelot at hipay.com

Aymeric
